/* CRIANDO A DATABASE DO DESAFIO */

CREATE DATABASE nivelamento_intuitive;

USE nivelamento_intuitive;

/* CRIANDO TABELA OPERADORAS*/

CREATE TABLE operadoras(
    Registro_ANS INT NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL,
    Razao_Social VARCHAR(255) NOT NULL,
    Nome_Fantasia VARCHAR(255),
    Modalidade VARCHAR(100) NOT NULL,
    Logradouro VARCHAR(255) NOT NULL,
    Numero VARCHAR(10),
    Complemento VARCHAR(255),
    Bairro VARCHAR(100),
    Cidade VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP VARCHAR(8),
    DDD CHAR(2),
    Telefone VARCHAR(15),
    Fax VARCHAR(15),
    Endereco_eletronico VARCHAR(255),
    Representante VARCHAR(255),
    Cargo_Representante VARCHAR(100),
    Regiao_de_Comercializacao INT,
    Data_Registro_ANS DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/*IMPORTANDO TABELA DE OPERADORAS*/

LOAD DATA INFILE "C:/Users/izael/Desktop/operadoras/operadoras_cadastradas.csv"
INTO TABLE operadoras FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

/* CRIANDO TABELA DE DEMONSTRACOES CONTABEIS */

CREATE TABLE demonstracoes_contabeis(
    DATA DATE NOT NULL,
    REG_ANS INT NOT NULL,
    CD_CONTA_CONTABIL INT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15, 2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL,
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/*O CAMINHO QUE USEI PODE SER DIFERENTE DO SEU,
MAS BASICAMENTE CRIEI UMA PASTA E COLOQUEI OS 4 ARQUIVOS
REFERENTES A 2024 E IMPORTEI TODOS COMO SQL*/

/*PODERIA TER IMPORTADO OS DE 2023 TAMBÉM MAS SERIA REDUNDANTE
E NÃO NECESSÁRIO PARA AS QUERIES ANÁLITICAS REQUISITADAS*/

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/1T2024.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/2T2024.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/3T2024.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/4T2024.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2023/1T2023.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2023/2t2023.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2023/3T2023.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2023/4T2023.csv"
INTO TABLE demonstracoes_contabeis FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

/* QUERIE SOBRE A PERGUNTA
    QUAIS AS 10 OPERADORAS COM MAIORES DESPESAS EM "EVENTOS/SINISTROS OU AVISADOS
    DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" NO ÚLTIMO TRIMESTRE?*/

SELECT
    o.Registro_ANS,
    o.Razao_Social,
    o.Nome_Fantasia,
    SUM(dc.VL_SALDO_FINAL) AS TOTAL_DESPESAS
FROM demonstracoes_contabeis dc
JOIN operadoras o ON dc.REG_ANS = o.Registro_ANS
WHERE dc.Descricao LIKE '%EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR %'
AND dc.DATA >= '2024-10-01'
AND dc.DATA <= '2024-12-31'
GROUP BY o.Registro_ANS, o.Razao_Social, o.Nome_Fantasia
ORDER BY TOTAL_DESPESAS DESC LIMIT 10;

/* QUERIE SOBRE A PERGUNTA
    QUAIS AS 10 OPERADORAS COM AS MAIORES DESPESAS NESSA CATEGORIA NO ÚLTIMO ANO?
*/

SELECT
    o.Registro_ANS,
    o.Razao_Social,
    o.Nome_Fantasia,
    SUM(dc.VL_SALDO_FINAL) AS TOTAL_DESPESAS
FROM demonstracoes_contabeis dc
JOIN operadoras o ON dc.REG_ANS = o.Registro_ANS
WHERE dc.Descricao LIKE '%EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR %'
AND dc.DATA >= '2024-01-01'
AND dc.DATA <= '2024-12-31'
GROUP BY o.Registro_ANS, o.Razao_Social, o.Nome_Fantasia
ORDER BY TOTAL_DESPESAS DESC LIMIT 10;


