CREATE DATABASE nivelamento_intuitive;

USE nivelamento_intuitive;

CREATE TABLE demonstracoes_contabeis_2024(
    DATA DATE,
    REG_ANS MEDIUMINT NOT NULL,
    CD_CONTA_CONTABIL INT NOT NULL,
    DESCRICAO MEDIUMTEXT NOT NULL,
    VL_SALDO_INICIAL FLOAT NOT NULL,
    VL_SALDO_FINAL FLOAT NOT NULL,
);

/*O CAMINHO QUE USEI PODE SER DIFERENTE DO SEU,
MAS BASICAMENTE CRIEI UMA PASTA E COLOQUEI OS 4 ARQUIVOS
REFERENTES A 2024 E IMPORTEI TODOS COMO SQL*/

/*PODERIA TER IMPORTADO OS DE 2023 TAMBÉM MAS SERIA REDUNDANTE
E NÃO NECESSÁRIO PARA AS QUERIES ANÁLITICAS REQUISITADAS*/

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/1T2024.csv"
INTO TABLE demonstracoes_contabeis_2024 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/2T2024.csv"
INTO TABLE demonstracoes_contabeis_2024 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/3T2024.csv"
INTO TABLE demonstracoes_contabeis_2024 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA INFILE "C:/Users/izael/Desktop/demonstracoes_2024/4T2024.csv"
INTO TABLE demonstracoes_contabeis_2024 FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;


